config/routes.rb
Rails.application.routes.draw do
  resources :cards  

  root 'home#index'
  post '/' => "home#check_translation"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :original_text, :translated_text, presence: true
 
  validate :original_and_translated_texts_are_not_equal 

  before_validation :set_review_date

  def check_translation(translation)
    self.translated_text == translation
  end

  def set_review_date
    self.review_date = DateTime.current + 3.days
  end

  private 
    
  def original_and_translated_texts_are_not_equal
    return unless original_text.strip.capitalize == translated_text.strip.capitalize
    errors.add(:original_text, "original and translated texts are equal")   
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception 
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all 
  end

  def new
    @card = Card.new 
  end 

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to cards_path
    else 
      render 'new'
    end 
  end

  def edit 
    @card = Card.find(params[:id])
  end
 
  def update 
    @card = Card.find(params[:id])
    if @card.update(card_params) 
      redirect_to cards_path 
    else 
      render 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    
    redirect_to cards_path     
  end

  private
 
  def card_params 
    params.require(:card).permit(:original_text, :translated_text, :review_date)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @random_card = Card.where("review_date <= ?", Date.today).order("RANDOM()").limit(1)
  end

  def check_translation
    @card = Card.find(params[:card_id])
    if @card.check_translation(params[:q])
      flash[:notice] = "Правильный перевод"
      @card.set_review_date
      @card.update(:review_date => @card.review_date)
    else 
      flash[:notice] = "Неправильный перевод" 
    end
    redirect_to root_path  
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :original_text %>
  <%= f.input :translated_text %>
  <%= f.submit 'отправить' %>
<% end %>

app/views/cards/edit.html.erb
<h3>Редактировать карточку</h3>
<%= render 'form' %>   

app/views/cards/index.html.erb
<table>
  <tr>
    <th>Слово</th>
    <th>Перевод</th>
    <th>Дата просмотра<th>
  </tr>
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime("%d/%m/%Y") %></td>
      <td><%= link_to "редактировать", edit_card_path(card) %></td>
      <td><%= link_to "удалить", card_path(card), method: :delete %>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h3>Добавить карточку</h3>
<%= render 'form' %>

app/views/home/index.html.erb
<p style="font-size: 22px;">
  Первый в мире удобный менеджер флеш-карточек. Именно так.
</p>
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<p> Оригинальный текст карты: </p>
<% @random_card.to_a.each do |random_card| %>
  <%= random_card.original_text %>
  <%= form_tag({controller: "home", action: "check_translation"}) do %>
    <%= label_tag(:q, "Введите перевод:") %>
    <%= text_field_tag(:q) %>
    <%= hidden_field_tag 'card_id', random_card.id %>
    <%= submit_tag("Проверить") %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="container">

      <header class="clearfix">
        <h1>Флэшкарточкер</h1>
        <ul class="navigation-links nav-pills">
          <li><%= link_to 'Все карточки', cards_path %></li>
          <li><%= link_to 'Добавить карточку', new_card_path %></li>
        </ul>
      </header>

      <section>
        <%= yield %>
      </section>

    </section>
  </body>
</html>